runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

beta_settings:
  cloud_sql_instances: bu-capstone-design

handlers:
  - url: /.*
    script: auto
